# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  controltec-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: control-mysql
    volumes:
      - controltec-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=controltec
      - MYSQL_USER=controltec
      - MYSQL_PASSWORD=123456

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: control-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - mysql